import Navbar from "@/components/layout/Navbar";
import { HeroSection } from "@/features/home/components/HeroSection";
import { ExamCarousel } from "@/features/home/components/ExamCarousel";
import { trendingExams, newExams } from "@/features/home/mockData";

export default function Home() {
  return (
    <div className="min-h-screen bg-slate-50 relative overflow-hidden flex flex-col">
      {/* Abstract Background Orbs for Premium Glassmorphism Feel */}
      <div className="absolute top-0 left-0 w-full h-[800px] overflow-hidden pointer-events-none z-0">
        <div className="absolute -top-[20%] -left-[10%] w-[50%] h-[50%] rounded-full bg-violet-400/20 blur-[120px] animate-pulse mix-blend-multiply" style={{ animationDuration: '8s' }} />
        <div className="absolute top-[10%] -right-[10%] w-[40%] h-[40%] rounded-full bg-indigo-400/20 blur-[100px] animate-pulse mix-blend-multiply" style={{ animationDuration: '10s' }} />
        <div className="absolute top-[40%] left-[20%] w-[30%] h-[30%] rounded-full bg-fuchsia-400/10 blur-[80px] animate-pulse mix-blend-multiply" style={{ animationDuration: '12s' }} />
      </div>

      {/* Background Image generated by AI */}
      <div 
        className="absolute top-0 left-0 w-full h-[600px] pointer-events-none opacity-40 mix-blend-overlay"
        style={{
          backgroundImage: "url('/images/hero-bg.png')",
          backgroundSize: "cover",
          backgroundPosition: "center bottom",
          maskImage: "linear-gradient(to bottom, black 40%, transparent 100%)",
          WebkitMaskImage: "linear-gradient(to bottom, black 40%, transparent 100%)",
        }}
      />

      <Navbar />
      
      <main className="relative z-10 flex-1">
        <HeroSection />
        
        <div className="mt-4 mb-24 space-y-12">
          <ExamCarousel 
            title="Trending Today" 
            subtitle="Những đề thi được tải xuống nhiều nhất trong 24h qua"
            emoji="🔥"
            exams={trendingExams}
          />
          
          <ExamCarousel 
            title="Mới Cập Nhật" 
            subtitle="Đề thi vừa được cộng đồng chia sẻ"
            emoji="🆕"
            exams={newExams}
          />
        </div>
      </main>
    </div>
  );
}
