import Navbar from "@/components/layout/Navbar";
import { HeroSection } from "@/features/home/components/HeroSection";
import { ExamCarousel } from "@/features/home/components/ExamCarousel";
import { trendingExams, newExams } from "@/features/home/mockData";
import { createClient } from "@/lib/supabase/server";

export default async function Home() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  let myExams: any[] = [];
  if (user) {
    const { data } = await supabase
      .from("GeneratedExams")
      .select("Id, Title, Subject, GradeLevel, DownloadCount, UpvoteCount")
      .eq("AuthorId", user.id)
      .order("CreatedAt", { ascending: false });
      
    if (data) {
      // Get vote status
      const examIds = data.map(d => d.Id);
      let votedExamIds = new Set<number>();
      
      if (examIds.length > 0) {
        const { data: userVotes } = await supabase
          .from("ExamVotes")
          .select("ExamId")
          .eq("UserId", user.id)
          .in("ExamId", examIds);
          
        if (userVotes) {
          userVotes.forEach(v => votedExamIds.add(v.ExamId));
        }
      }

      myExams = data.map(exam => ({
        id: exam.Id.toString(),
        title: exam.Title || "Đề thi chưa đặt tên",
        subject: exam.Subject || "Chung",
        grade: `Lớp ${exam.GradeLevel}`,
        school: "YourExam",
        downloads: exam.DownloadCount || 0,
        upvotes: exam.UpvoteCount || 0,
        tags: [exam.Subject, `Lớp ${exam.GradeLevel}`].filter(Boolean),
        hasUpvoted: votedExamIds.has(exam.Id)
      }));
    }
  }
  return (
    <div className="min-h-screen bg-slate-50 relative overflow-hidden flex flex-col">
      {/* Abstract Background Orbs for Premium Glassmorphism Feel */}
      <div className="absolute top-0 left-0 w-full h-[800px] overflow-hidden pointer-events-none z-0">
        <div className="absolute -top-[20%] -left-[10%] w-[50%] h-[50%] rounded-full bg-violet-400/20 blur-[120px] animate-pulse mix-blend-multiply" style={{ animationDuration: '8s' }} />
        <div className="absolute top-[10%] -right-[10%] w-[40%] h-[40%] rounded-full bg-indigo-400/20 blur-[100px] animate-pulse mix-blend-multiply" style={{ animationDuration: '10s' }} />
        <div className="absolute top-[40%] left-[20%] w-[30%] h-[30%] rounded-full bg-fuchsia-400/10 blur-[80px] animate-pulse mix-blend-multiply" style={{ animationDuration: '12s' }} />
      </div>

      {/* Background Image generated by AI */}
      <div 
        className="absolute top-0 left-0 w-full h-[600px] pointer-events-none opacity-40 mix-blend-overlay"
        style={{
          backgroundImage: "url('/images/hero-bg.png')",
          backgroundSize: "cover",
          backgroundPosition: "center bottom",
          maskImage: "linear-gradient(to bottom, black 40%, transparent 100%)",
          WebkitMaskImage: "linear-gradient(to bottom, black 40%, transparent 100%)",
        }}
      />

      <Navbar />
      
      <main className="relative z-10 flex-1">
        <HeroSection />
        
        <div className="mt-4 mb-24 space-y-12">
          <ExamCarousel 
            title="Trending Today" 
            subtitle="Những đề thi được tải xuống nhiều nhất trong 24h qua"
            emoji="🔥"
            exams={trendingExams}
          />
          
          <ExamCarousel 
            title="Mới Cập Nhật" 
            subtitle="Đề thi vừa được cộng đồng chia sẻ"
            emoji="🆕"
            exams={newExams}
          />

          {user && myExams.length > 0 && (
            <ExamCarousel 
              title="Đề thi của bạn" 
              subtitle="Danh sách các đề thi bạn đã thiết kế và lưu lại"
              emoji="📚"
              exams={myExams}
            />
          )}
        </div>
      </main>
    </div>
  );
}
