import Navbar from "@/components/layout/Navbar";
import { HeroSection } from "@/features/home/components/HeroSection";
import { ExamCarousel } from "@/features/home/components/ExamCarousel";
import { trendingExams, newExams } from "@/features/home/mockData";

export default function Home() {
  return (
    <div className="min-h-screen bg-slate-50 relative overflow-hidden flex flex-col">
      {/* Background Image generated by AI */}
      <div 
        className="absolute top-0 left-0 w-full h-[600px] pointer-events-none"
        style={{
          backgroundImage: "url('/images/hero-bg.png')",
          backgroundSize: "cover",
          backgroundPosition: "center bottom",
          maskImage: "linear-gradient(to bottom, black 50%, transparent 100%)",
          WebkitMaskImage: "linear-gradient(to bottom, black 50%, transparent 100%)",
        }}
      />

      <Navbar />
      
      <main className="relative z-10 flex-1">
        <HeroSection />
        
        <div className="mt-4 mb-24 space-y-12">
          <ExamCarousel 
            title="Trending Today" 
            subtitle="Những đề thi được tải xuống nhiều nhất trong 24h qua"
            emoji="🔥"
            exams={trendingExams}
          />
          
          <ExamCarousel 
            title="Mới Cập Nhật" 
            subtitle="Đề thi vừa được cộng đồng chia sẻ"
            emoji="🆕"
            exams={newExams}
          />
        </div>
      </main>
    </div>
  );
}
