import Navbar from "@/components/layout/Navbar";

export default function DocumentsPage() {
  return (
    <div className="min-h-screen bg-slate-50 relative overflow-hidden flex flex-col font-sans">
      {/* Abstract Background Orbs for Premium Glassmorphism Feel */}
      <div className="absolute top-0 left-0 w-full h-[800px] overflow-hidden pointer-events-none z-0">
        <div className="absolute -top-[20%] -left-[10%] w-[50%] h-[50%] rounded-full bg-violet-400/20 blur-[120px] animate-pulse mix-blend-multiply" style={{ animationDuration: '8s' }} />
        <div className="absolute top-[10%] -right-[10%] w-[40%] h-[40%] rounded-full bg-indigo-400/20 blur-[100px] animate-pulse mix-blend-multiply" style={{ animationDuration: '10s' }} />
        <div className="absolute top-[40%] left-[20%] w-[30%] h-[30%] rounded-full bg-fuchsia-400/10 blur-[80px] animate-pulse mix-blend-multiply" style={{ animationDuration: '12s' }} />
      </div>

      {/* Background Image generated by AI */}
      <div 
        className="absolute top-0 left-0 w-full h-[600px] pointer-events-none opacity-40 mix-blend-overlay"
        style={{
          backgroundImage: "url('/images/hero-bg.png')",
          backgroundSize: "cover",
          backgroundPosition: "center bottom",
          maskImage: "linear-gradient(to bottom, black 40%, transparent 100%)",
          WebkitMaskImage: "linear-gradient(to bottom, black 40%, transparent 100%)",
        }}
      />

      <Navbar />
      
      <main className="relative z-10 flex-1 flex items-center justify-center">
        <div className="text-center p-12 bg-white/50 backdrop-blur-md rounded-3xl border border-white/60 shadow-xl max-w-lg w-full mx-4">
          <div className="w-16 h-16 bg-indigo-100 rounded-full flex items-center justify-center mx-auto mb-6">
            <svg className="w-8 h-8 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
            </svg>
          </div>
          <h1 className="text-3xl font-extrabold text-slate-900 mb-4 font-heading">Kho Tài Liệu</h1>
          <p className="text-lg text-slate-600">
            Chức năng chia sẻ và lưu trữ tài liệu (Word, PDF) đang được phát triển và sẽ sớm ra mắt.
          </p>
        </div>
      </main>
    </div>
  );
}
